# Conclusion

This research targets at the development of electric vehicle market in Washington (WA) State from 1997 to 2023. It involves analysis of market shares for each brand, analysis of electric range, and visualization of the geographic distribution for registered electric vehicles in WA. The overall market size of electric vehicles is continuously growing from 2012 to 2022. Most Manufacturers switched from selling Plug-in Hybrid Electric Vehicles (PHEV) to mainly sell Battery Electric Vehicles (BEV) during this time, and BEV dominated the market in this period. Among all car manufacturers, TESLA, NISSAN, CHEVROLET, KIA, and VOLKSWAGEN are the top five players in the electric vehicle market, and TESLA has been the largest brand in WA since 2018 and owns more than 50% of the market share in 2022. In addition to market size, electric range has also been well researched. Although there are some fluctuations in the growth of electric range over the years, overall, both BEV and PHEV show an increasing trend in electric range. Also, Clean Alternative Fuel Vehicle increased dramatically, by 50% each year, after 2019. King, Pierce, Thurston, Kitsap, Mason, Whatcom, Clark, and Cowlitz are identified as regions where most electric vehicles are distributed within Washington State. In short, BEV is becoming the mainstream in electric vehicles industry, and TESLA is now the largest brand in the Washington State. In the past few years, electric range of BEV has been greatly improved and more and more electric vehicles are now Clean Alternative Fuel Eligible. In Washington State, electric vehicles are mostly distributed around cities like Seattle, and Tacoma, etc. 