--- 
title: "Electric Vehicle Analysis"
author: "Yaohong Liang, Zhongyuan Ye, Shuyu He"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

With the development in battery and charging technologies, electrical vehicles, defined as vehicles using more than one electric motor for propulsion ([1](https://en.wikipedia.org/wiki/Electric_vehicle)), are becoming a more prominent competitor in the automotive market. It is an observable trend that the global electric vehicle market has been expanding quickly in recent years. With the main advantages of being environmentally friendly and lower maintenance costs, electric vehicles have become a preferable choice for vehicle customers. Tesla, known as the biggest manufacturer in the electric cars market, has taken the majority of the market; many traditional fuel-based car manufacturers, such as Chevrolet and Ford, also started to sell electric vehicles. 

To better understand the development of the electric vehicle market, we choose to study the data of electric vehicles registered in WA from 1997 to 2023. Electric cars have two categories based on their power source: battery electric vehicles (BEVs) and plug-in hybrid electric vehicles (PHEVs). BEVs are powered by electricity only, while PHEVs use electricity and other fuels, such as gasoline or diesel, to power the engine ([2](https://data.wa.gov/Transportation/Electric-Vehicle-Population-Data/f6w7-q2d2)). This research will use multiple data visualization techniques to study the development of battery electric vehicles and plug-in hybrid electric vehicles registered in Washington state. In addition, the research will analyze several factors, including electric vehicle manufacturers, geographical distribution, and electric range, to understand the change in the electric vehicle market.


